apiVersion: apps/v1
kind: Deployment
metadata:
  name: ian-app
  namespace: lab1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ian-app
  template:
    metadata:
      labels:
        app: ian-app
    spec:
      containers:
      - name: ian-app
        image: testcontainers/helloworld:latest
        ports:
        - containerPort: 8080