apiVersion: v1
kind: Service
metadata:
  name: echo-service-deployment-svc
  namespace: lab1
spec:
  selector:
    app: echo-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
