apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dirc-app
  namespace: argocd
spec:
  project: dirc
  source:
    repoURL: 'https://github.com/cinqict/gitops-workshop'
    targetRevision: gitops-dirc
    path: lab1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lab1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
