apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouke-app
  namespace: argocd  # This should match where Argo CD is installed
spec:
  project: default

  source:
    repoURL: https://github.com/cinqict/gitops-workshop.git
    targetRevision: main
    path: lab1/bouke-app/

  destination:
    server: https://kubernetes.default.svc
    namespace: lab1