apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cinqict/gitops-workshop.git
    targetRevision: HEAD
    path: lab1/echo-application
  destination:
    server: https://kubernetes.default.svc
    namespace: lab1
