apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lab1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: lab1/gitops-app/
    repoURL: https://github.com/cinqict/gitops-workshop.git
    targetRevision: HEAD
