apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billion-dollar-app
  namespace: lab1
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lab1
  project: default
  source:
    path: lab1/hello-app
    repoURL: https://github.com/cinqict/gitops-workshop.git